spring.application.name=bookings
server.port=${PORT:5050}

##DataBase Configuration
spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

