spring.application.name=bookings
server.port=5050

##DataBase Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/bookings
spring.datasource.username=root
spring.datasource.password=Vijaybalaji@123

